:concurrency: 5
:max_retries: 1
:queues:
  - [mailers, 4]
  - [default, 2]
  - [newsletter, 2]
  - [newsletters_opt_in, 2]
  - [conference_diplomas, 2]
  - [decidim_events, 2]
  - [events, 2]
  - [user_report, 2]
  - [block_user, 2]
  - [metrics, 1]
  - [exports, 1]
  - [translations, 1]
  - [ vote_reminder, 2 ]
  - [ reminders, 2 ]
  - [ close_meeting_reminder, 1 ]